---
aws_region:     "ap-southeast-2"
vpc_name:       "Bahmni_Dev_Infra"
vpc_account: "3931-2853-5479"
VpcInstanceTenancy: "dedicated"
aws_access_key:  AKIAJQSIN5HKCZHLQ3KA
aws_secret_key: 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

#Cidr Block
infra_cidr_blocks:
  vpc_cidr_block: 172.21.0.0/16
  public_subnet_1: 172.21.0.0/24
  tw_bangalore_Airtel_ip: 182.74.238.30/32
  tw_bangalore_Tcl_ip: 14.142.51.155/32
  tw_hyd_Airtel_ip: 121.244.62.198/32
  tw_hyd_Tcl_ip: 182.74.95.82/32
  all: 0.0.0.0/0

cidr_blocks:
  assets_subnet_1: 172.21.1.0/24
  build_agents_subnet_1: 172.21.2.0/24
  qa_subnet_1: 172.21.3.0/24
  showcase_subnet_1: 172.21.4.0/24

#Security groups definition
#Bastion Security Group
bastion_rules :
  - proto: tcp
    from_port: 22
    to_port: 22
    cidr_ip: "{{infra_cidr_blocks.tw_bangalore_Airtel_ip}}"
  - proto: tcp
    from_port: 22
    to_port: 22
    cidr_ip: "{{infra_cidr_blocks.tw_bangalore_Tcl_ip}}"
  - proto: tcp
    from_port: 22
    to_port: 22
    cidr_ip: "{{infra_cidr_blocks.tw_hyd_Airtel_ip}}"
  - proto: tcp
    from_port: 22
    to_port: 22
    cidr_ip: "{{infra_cidr_blocks.tw_hyd_Tcl_ip}}"

bastion_rules_egress :
  - proto: tcp
    from_port: 0
    to_port: 65535
    cidr_ip: "{{ infra_cidr_blocks.all }}"

#Bahmni Security group
bahmni_rules:
  - proto: tcp
    from_port: 80
    to_port: 80
    cidr_ip: "{{infra_cidr_blocks.vpc_cidr_block}}"
  - proto: tcp
    from_port: 443
    to_port: 443
    cidr_ip: "{{infra_cidr_blocks.vpc_cidr_block}}"
  - proto: tcp
    from_port: 1024
    to_port: 65535
    cidr_ip: "{{infra_cidr_blocks.vpc_cidr_block}}"
  - proto: tcp
    from_port: 22
    to_port: 22
    group_name: "{{sg_bastion_group.group_id}}"

bahmni_rules_egress :
  - proto: tcp
    from_port: 0
    to_port: 65535
    cidr_ip: "{{ infra_cidr_blocks.all }}"

##Public Security Group
#public_proxy_rules :
#  - proto: tcp
#    from_port: 80
#    to_port: 80
#    cidr_ip: "{{infra_cidr_blocks.tw_bangalore_Airtel_ip}}"
#  - proto: tcp
#    from_port: 80
#    to_port: 80
#    cidr_ip: "{{infra_cidr_blocks.tw_bangalore_Tcl_ip}}"
#  - proto: tcp
#    from_port: 443
#    to_port: 443
#    cidr_ip: "{{infra_cidr_blocks.tw_bangalore_Airtel_ip}}"
#  - proto: tcp
#    from_port: 443
#    to_port: 443
#    cidr_ip: "{{infra_cidr_blocks.tw_bangalore_Tcl_ip}}"
#  - proto: tcp
#    from_port: 80
#    to_port: 80
#    cidr_ip: "{{infra_cidr_blocks.tw_hyd_Airtel_ip}}"
#  - proto: tcp
#    from_port: 80
#    to_port: 80
#    cidr_ip: "{{infra_cidr_blocks.tw_hyd_Tcl_ip}}"
#  - proto: tcp
#    from_port: 443
#    to_port: 443
#    cidr_ip: "{{infra_cidr_blocks.tw_hyd_Airtel_ip}}"
#  - proto: tcp
#    from_port: 443
#    to_port: 443
#    cidr_ip: "{{infra_cidr_blocks.tw_hyd_Tcl_ip}}"
#  - proto: tcp
#    from_port: 22
#    to_port: 22
#    group_name: "{{sg_bastion_group.group_id}}"
#public_proxy_rules_egress :
#  - proto: tcp
#    from_port: 0
#    to_port: 65535
#    cidr_ip: "{{infra_cidr_blocks.all}}"

#Tw Proxy Security Group
tw_proxy_rules :
  - proto: tcp
    from_port: 80
    to_port: 80
    cidr_ip: "{{infra_cidr_blocks.tw_bangalore_Airtel_ip}}"
  - proto: tcp
    from_port: 80
    to_port: 80
    cidr_ip: "{{infra_cidr_blocks.tw_bangalore_Tcl_ip}}"
  - proto: tcp
    from_port: 443
    to_port: 443
    cidr_ip: "{{infra_cidr_blocks.tw_bangalore_Airtel_ip}}"
  - proto: tcp
    from_port: 443
    to_port: 443
    cidr_ip: "{{infra_cidr_blocks.tw_bangalore_Tcl_ip}}"
  - proto: tcp
    from_port: 80
    to_port: 80
    cidr_ip: "{{infra_cidr_blocks.tw_hyd_Airtel_ip}}"
  - proto: tcp
    from_port: 80
    to_port: 80
    cidr_ip: "{{infra_cidr_blocks.tw_hyd_Tcl_ip}}"
  - proto: tcp
    from_port: 443
    to_port: 443
    cidr_ip: "{{infra_cidr_blocks.tw_hyd_Airtel_ip}}"
  - proto: tcp
    from_port: 443
    to_port: 443
    cidr_ip: "{{infra_cidr_blocks.tw_hyd_Tcl_ip}}"
  - proto: tcp
    from_port: 22
    to_port: 22
    group_name: "{{sg_bastion_group.group_id}}"
tw_proxy_rules_egress :
  - proto: tcp
    from_port: 0
    to_port: 65535
    cidr_ip: "{{ infra_cidr_blocks.all }}"


