---

- ec2_remote_facts:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    region:           "{{ aws_region }}"
    filters:
      instance-state-name: running
      "tag:Name": proxy-server
  register: proxy_instance_fact

- debug: msg="{{ proxy_instance_fact }}"


- name: Add proxy to dynamic host group
  add_host:
    name: proxyhost
    groupname: gatewayed
    ansible_ssh_host: "{{ proxy_instance_fact.instances[0].private_ip_address }}"
    ansible_user: centos

- name: install haproxy
  delegate_to: proxyhost
  become: yes
  yum: name=haproxy state=present
  tags: proxy-provision

- name: start haproxy
  delegate_to: proxyhost
  become: yes
  service: name=haproxy state=started
  tags: proxy-provision

- name: Copy haproxy config
  delegate_to: proxyhost
  become: yes
  template:
    src=haproxy.cfg.j2
    dest=/etc/haproxy/haproxy.cfg
    backup=yes
    mode=755

- name: Restart haproxy
  delegate_to: proxyhost
  become: yes
  service: name=haproxy state=reloaded
  tags: proxy-provision

- name: stop iptables in proxy server
  delegate_to: proxyhost
  become: yes
  service: name=iptables state=stopped
  tags: proxy-provision