- hosts: localhost
  vars_files:
     - "../../group_vars/secure_vars.yml"
  tasks:
  - name: terminate deployment instance
    include: ../terminate_instance.yml
    vars:
      - instance_name: "{{ deploy_instances[0] }}"

  - name: terminate deployment instance
    include: ../terminate_instance.yml
    vars:
      - instance_name: "{{ deploy_instances[1] }}"
