- name:               Set up public subnet route table
  ec2_vpc_route_table:
    vpc_id:           "{{ vpc_id }}"
    region:           "{{ aws_region }}"
    aws_access_key:   "{{ aws_access_key }}"
    aws_secret_key:   "{{ aws_secret_key }}"
    tags:
      Name:           "Public"
    subnets: "{{infra_cidr_blocks.public_subnet_1}}"
    routes:
      - dest:         "{{infra_cidr_blocks.all}}"
        gateway_id:   "{{ igw_id }}"

- name:               Setup Nat route table
  ec2_vpc_route_table:
    vpc_id:           "{{ vpc_id }}"
    region:           "{{ aws_region }}"
    aws_access_key:   "{{ aws_access_key }}"
    aws_secret_key:   "{{ aws_secret_key }}"
    state: present
    tags:
      Name:           "Outbound from vpc_default"
    subnets:
      - "{{ assets_subnet_id }}"
      - "{{ qa_subnet_id }}"
      - "{{ build_agents_subnet_id }}"
      - "{{ showcase_subnet_id }}"
    routes:
        - dest:        "{{infra_cidr_blocks.all}}"
          gateway_id: "{{nat_output['NatGateway']['NatGatewayId']}}"
  register: route_table

- name: Update Route Table
  environment:
      AWS_ACCESS_KEY_ID: "{{ aws_access_key }}"
      AWS_SECRET_ACCESS_KEY: "{{ aws_secret_key }}"
  shell: "aws ec2 replace-route --region {{aws_region}} --route-table-id {{route_table['route_table']['id']}} --destination-cidr-block {{infra_cidr_blocks.all}} --nat-gateway-id {{nat_output['NatGateway']['NatGatewayId']}}"




